#
#   InflectionFeatureOperations.pyi
#
#   Type stubs for InflectionFeatureOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations

class InflectionFeatureOperations(BaseOperations[Any]):
    """InflectionFeatureOperations operations"""

    # NOTE: this class does not define its own GetAll -- it inherits whatever
    # BaseOperations provides (see BaseOperations.pyi). The previous
    # `GetAll(...) -> Iterator[Any]` line here asserted an override that
    # does not exist in the runtime implementation.
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def DescribeFeatStruc(self, fs_or_spec: Any, slot: Optional[str] = None) -> str: ...
    def GetInflectableFeatures(self, pos_or_hvo: Any) -> list: ...
    def GetFeatureType(self, feature_or_hvo: Any) -> Optional[str]: ...
    def InflectionClassGetName(self, ic_or_hvo: Any, wsHandle: Any = None) -> str: ...
    def InflectionClassSetName(self, ic_or_hvo: Any, name: str, wsHandle: Any = None) -> None: ...
    def InflectionClassGetAbbreviation(self, ic_or_hvo: Any, wsHandle: Any = None) -> str: ...
    def InflectionClassSetAbbreviation(self, ic_or_hvo: Any, abbr: str, wsHandle: Any = None) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
