#
#   MorphRuleOperations.pyi
#
#   Type stubs for MorphRuleOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations, EnumerableWrapper
from .compound_rule_collection import CompoundRuleCollection
from .affix_template_collection import AffixTemplateCollection

class MorphRuleOperations(BaseOperations[Any]):
    """MorphRuleOperations operations"""

    def GetAll(self) -> EnumerableWrapper[Any]: ...
    def GetAllCompoundRules(self) -> CompoundRuleCollection: ...
    def GetAllAffixTemplates(self) -> AffixTemplateCollection: ...
    def GetAllAffixTemplatesForPOS(self, pos_or_hvo: Any) -> AffixTemplateCollection: ...
    def GetAllAdhocCoProhibitions(self) -> EnumerableWrapper[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def __getattr__(self, name: str) -> Any: ...
