#
#   PhonologicalRuleOperations.pyi
#
#   Type stubs for PhonologicalRuleOperations
#

from typing import Any, Optional, Iterator, TYPE_CHECKING
from ..BaseOperations import BaseOperations
from .rule_collection import RuleCollection

if TYPE_CHECKING:
    from ..System.phonological_context import PhonologicalContext
    from ..System.rule_feature import RuleFeatureCollection

class PhonologicalRuleOperations(BaseOperations[Any]):
    """PhonologicalRuleOperations operations"""

    def GetAll(self) -> RuleCollection: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, item_or_hvo: Any, insert_after: bool = True, deep: bool = True) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def GetLeftContext(self, rule_or_hvo: Any, rhs_index: int = 0) -> Optional["PhonologicalContext"]: ...
    def GetRightContext(self, rule_or_hvo: Any, rhs_index: int = 0) -> Optional["PhonologicalContext"]: ...
    def GetInputPOSes(self, rule_or_hvo: Any, rhs_index: int = 0) -> list: ...
    def GetRequiredRuleFeatures(self, rule_or_hvo: Any, rhs_index: int = 0) -> "RuleFeatureCollection": ...
    def GetExcludedRuleFeatures(self, rule_or_hvo: Any, rhs_index: int = 0) -> "RuleFeatureCollection": ...
    def IsDisabled(self, rule_or_hvo: Any) -> bool: ...
    def SetDisabled(self, rule_or_hvo: Any, disabled: bool) -> None: ...
    def DescribeRule(self, rule_or_hvo: Any) -> str: ...
    def __getattr__(self, name: str) -> Any: ...
