#
#   PhonologicalRuleOperations.pyi
#
#   Type stubs for PhonologicalRuleOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations
from .rule_collection import RuleCollection

class PhonologicalRuleOperations(BaseOperations[Any]):
    """PhonologicalRuleOperations operations"""

    def GetAll(self) -> RuleCollection: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def __getattr__(self, name: str) -> Any: ...
