#
#   SegmentOperations.pyi
#
#   Type stubs for SegmentOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations, EnumerableWrapper

class SegmentOperations(BaseOperations[Any]):
    """SegmentOperations operations"""

    def GetAll(self, paragraph_or_hvo: Any) -> EnumerableWrapper[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def GetAnalyses(self, segment_or_hvo: Any) -> list: ...
    def SetAnalysis(self, segment_or_hvo: Any, index: int, analysis_or_hvo: Any) -> None: ...
    def ReplaceAnalysis(self, segment_or_hvo: Any, old_analysis_or_hvo: Any, new_analysis_or_hvo: Any) -> None: ...
    def InsertAnalysis(self, segment_or_hvo: Any, index: int, analysis_or_hvo: Any) -> None: ...
    def AppendAnalysis(self, segment_or_hvo: Any, analysis_or_hvo: Any) -> None: ...
    def RemoveAnalysis(self, segment_or_hvo: Any, index: int) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
