#
#   OverlayOperations.pyi
#
#   Type stubs for OverlayOperations
#

from typing import Any, List, Optional, Iterator
from ..BaseOperations import BaseOperations

class OverlayOperations(BaseOperations[Any]):
    """OverlayOperations operations"""

    # Inherited from PossibilityItemOperations.GetAll (list[ICmPossibility]).
    def GetAll(self) -> List[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def __getattr__(self, name: str) -> Any: ...
