#
#   PossibilityListOperations.pyi
#
#   Type stubs for PossibilityListOperations
#

from typing import Any, List, Optional, Iterator
from ..BaseOperations import BaseOperations

class PossibilityListOperations(BaseOperations[Any]):
    """PossibilityListOperations operations"""

    # NOTE: this class has no GetAll of its own; it defines GetAllLists()
    # instead (see below). The previous `GetAll(...) -> Iterator[Any]` line
    # here asserted an override that does not exist in the runtime
    # implementation.
    def GetAllLists(self) -> List[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, obj: Any, deep: bool = True) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def __getattr__(self, name: str) -> Any: ...
