#
#   PublicationOperations.pyi
#
#   Type stubs for PublicationOperations
#

from typing import Any, List, Optional, Iterator
from ..BaseOperations import BaseOperations

class PublicationOperations(BaseOperations[Any]):
    """PublicationOperations operations"""

    def GetAll(self, recursive: bool = True, **kwargs: Any) -> List[Any]: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, item_or_hvo: Any, insert_after: bool = True, deep: bool = False) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def __getattr__(self, name: str) -> Any: ...
