#
#   AllomorphOperations.pyi
#
#   Type stubs for AllomorphOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations
from .allomorph_collection import AllomorphCollection

class AllomorphOperations(BaseOperations[Any]):
    """AllomorphOperations operations"""

    def GetAll(self, entry_or_hvo: Any = None) -> AllomorphCollection: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, item_or_hvo: Any, insert_after: bool = True, deep: bool = False) -> Any: ...
    def RemoveOrphaned(self, entry: Any = None, progress: Any = None) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def GetOwningEntry(self, allomorph_or_hvo: Any) -> Optional[Any]: ...
    def GetStemName(self, allo_or_hvo: Any) -> Optional[Any]: ...
    def SetStemName(self, allo_or_hvo: Any, stem_name_or_hvo_or_None: Any) -> Any: ...
    # Inflection-class membership (issue #581): stem allomorphs only;
    # GetInflectionClasses returns [] for non-stem allomorphs or unset.
    def GetInflectionClasses(self, allo_or_hvo: Any) -> list: ...
    def AddInflectionClass(self, allo_or_hvo: Any, infl_class_or_hvo: Any) -> None: ...
    def RemoveInflectionClass(self, allo_or_hvo: Any, infl_class_or_hvo: Any) -> None: ...
    # Required features (issue #581): MsEnvFeaturesOA round-trip. Getter
    # returns None (unset/wrong type), {} (present-but-empty), or a
    # MakeFeatStruc-shaped {feature_guid: value_guid | {...}} dict.
    def GetRequiredFeatures(self, allo_or_hvo: Any) -> Optional[dict]: ...
    def SetRequiredFeatures(self, allo_or_hvo: Any, spec: dict, struct_guid: Optional[str] = None) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
