#
#   AllomorphOperations.pyi
#
#   Type stubs for AllomorphOperations
#

from typing import Any, Optional, Iterator
from ..BaseOperations import BaseOperations
from .allomorph_collection import AllomorphCollection

class AllomorphOperations(BaseOperations[Any]):
    """AllomorphOperations operations"""

    def GetAll(self, entry_or_hvo: Any = None) -> AllomorphCollection: ...
    def Find(self, *args: Any, **kwargs: Any) -> Optional[Any]: ...
    def Exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def Create(self, *args: Any, **kwargs: Any) -> Any: ...
    def Delete(self, obj: Any) -> None: ...
    def Duplicate(self, item_or_hvo: Any, insert_after: bool = True, deep: bool = False) -> Any: ...
    def RemoveOrphaned(self, entry: Any = None, progress: Any = None) -> Any: ...
    def GetName(self, obj: Any) -> Optional[str]: ...
    def SetName(self, obj: Any, name: str) -> None: ...
    def GetGUID(self, obj: Any) -> Optional[str]: ...
    def GetOwningEntry(self, allomorph_or_hvo: Any) -> Optional[Any]: ...
    def __getattr__(self, name: str) -> Any: ...
